server:
  port: 10012
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.189.141:3307/db_data?characterEncoding=UTF8&ServerTimezone=UTC
    username: root
    password: qfjava
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: JobProvider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070